name=esp32-rfid-switch
version=0.1.0
author=matthias-bs
maintainer=matthias-bs
sentence=Controls a switch (e.g. relay) by presence of a UHF RFID Tag.
paragraph=Controls a local relay or Shelly switch from a validated UHF RFID tag, with optional BLE address or name-based Shelly configuration.
category=Communication
url=https://github.com/matthias-bs/esp32-rfid-switch
architectures=esp32
includes=rfid_switch_webconfig.h
depends=M5Unit-UHF-RFID,esp32-shelly-ble-rpc,NimBLE-Arduino,GDTouchKeyboard
